[project]
name='gestao-pessoal'
version='0.1.0'
description="site para gestão pessoal"
requires-python=">=3.13"
dependencies=[
    "django>=5.2.3",
    "djangorestframework>=3.16.0",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "python-decouple>=3.8",
]
