# Generated by Django 5.2.3 on 2025-06-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateField()),
                ('data_criacao', models.DateField()),
                ('parcela', models.FloatField()),
                ('grupo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.grupo')),
                ('metodos_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.metodos')),
                ('pessoa_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoa')),
            ],
        ),
    ]
