# Generated by Django 5.2.3 on 2025-06-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('metodo', models.CharField(choices=[('AV', 'À Vista'), ('AP', 'À Prazo'), ('MS', 'Mensal')], default='AV', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Avista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('avista_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Aprazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('parcelas', models.IntegerField()),
                ('aprazo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.despesa')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='grupo_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.grupo'),
        ),
        migrations.CreateModel(
            name='Mensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_pagamento', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('mensal_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.despesa')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='metodos_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.metodos'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='pessoa_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.pessoa'),
        ),
    ]
