# Generated by Django 5.2.3 on 2025-06-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='metodo',
            new_name='metodo_pagamento',
        ),
    ]
